-- 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME)을 출력
SELECT
    II.ITEM_ID,
    II.ITEM_NAME
FROM ITEM_INFO AS II
LEFT JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.ITEM_ID
-- ROOT 아이템
WHERE IT.PARENT_ITEM_ID IS NULL
-- 아이템 ID를 기준으로 오름차순 정렬
ORDER BY ITEM_ID;
