-- 년, 월, 성별 별로 상품을 구매한 회원수를 집계
SELECT
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    U.GENDER,
    COUNT(DISTINCT O.USER_ID) AS USERS
FROM ONLINE_SALE AS O
JOIN USER_INFO AS U
ON O.USER_ID = U.USER_ID
-- 성별 정보가 없는 경우 결과에서 제외
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
-- 년, 월, 성별을 기준으로 오름차순 정렬
ORDER BY YEAR, MONTH, GENDER;
