-- 대장균 개체의 ID(ID)와 자식의 수(CHILD_COUNT)
SELECT
    P.ID,
    COUNT(E.ID) AS CHILD_COUNT
FROM ECOLI_DATA AS P
LEFT JOIN ECOLI_DATA AS E ON P.ID = E.PARENT_ID
GROUP BY P.ID
-- 개체의 ID 에 대해 오름차순 정렬
ORDER BY P.ID;
