-- 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상
WITH MORE_THAN_5RENTS AS (
    SELECT
        CAR_ID,
        COUNT(*) AS CNT_RENTS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING CNT_RENTS >= 5
)
-- 월별 자동차 ID 별 총 대여 횟수
SELECT
    MONTH(C.START_DATE) AS MONTH,
    M.CAR_ID,
    COUNT(*) AS RECORDS
FROM MORE_THAN_5RENTS AS M
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C ON M.CAR_ID = C.CAR_ID
-- 해당 기간 동안
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
-- 월을 기준으로 오름차순 정렬, 월이 같다면 자동차 ID를 기준으로 내림차순 정렬
ORDER BY MONTH, CAR_ID DESC;
