WITH RECURSIVE RECUR_ECOLI AS (
    SELECT
        ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
        E.ID,
        R.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA AS E
    JOIN RECUR_ECOLI AS R ON E.PARENT_ID = R.ID
)
SELECT
-- 개체의 수(COUNT)와 세대(GENERATION)
    COUNT(DISTINCT R.ID) AS COUNT,
    R.GENERATION
FROM RECUR_ECOLI AS R
LEFT JOIN ECOLI_DATA AS E ON R.ID = E.PARENT_ID
-- 각 세대별 자식이 없는
WHERE E.ID IS NULL
GROUP BY R.GENERATION
-- 세대에 대해 오름차순 정렬
ORDER BY R.GENERATION
