-- 물고기의 이름과 잡은 수
SELECT
    COUNT(F.ID) AS FISH_COUNT,
    N.FISH_NAME
FROM FISH_INFO AS F
JOIN FISH_NAME_INFO AS N
ON F.FISH_TYPE = N.FISH_TYPE
-- 물고기의 종류별
GROUP BY FISH_NAME
-- 잡은 수 기준으로 내림차순 정렬
ORDER BY FISH_COUNT DESC;
