-- 대장균의 ID(ID), 대장균의 형질(GENOTYPE), 부모 대장균의 형질(PARENT_GENOTYPE)
SELECT
    E.ID,
    E.GENOTYPE,
    P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS E
LEFT JOIN ECOLI_DATA AS P ON E.PARENT_ID = P.ID
-- 부모의 형질을 모두 보유한
WHERE E.GENOTYPE & P.GENOTYPE = P.GENOTYPE
-- ID에 대해 오름차순 정렬
ORDER BY ID;
