-- 각 분기(QUARTER)별 분화된 대장균의 개체의 총 수(ECOLI_COUNT)
SELECT
    CONCAT(QUARTER(DIFFERENTIATION_DATE),'Q') AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
-- 분기에 대해 오름차순으로 정렬
ORDER BY QUARTER
