-- 상품코드 별 매출액(판매가 * 판매량) 합계
SELECT
    P.PRODUCT_CODE,
    P.PRICE * SUM(OS.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P
JOIN OFFLINE_SALE AS OS ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_ID
-- 매출액을 기준으로 내림차순 정렬해주시고 매출액이 같다면 상품코드를 기준으로 오름차순 정렬
ORDER BY SALES DESC, PRODUCT_CODE;
