-- 상품을 구매한 회원수와 상품을 구매한 회원의 비율을 년, 월 별로 출력
SELECT
    YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
    -- 상품을 구매한 회원의 비율은 소수점 두번째자리에서 반올림
    ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021'), 1) AS PUCHASED_RATIO
FROM USER_INFO AS UI
JOIN ONLINE_SALE AS OS ON UI.USER_ID = OS.USER_ID
-- 2021년에 가입한 전체 회원들
WHERE YEAR(UI.JOINED) = '2021'
GROUP BY YEAR, MONTH
-- 전체 결과는 년을 기준으로 오름차순 정렬, 년이 같다면 월을 기준으로 오름차순 정렬
ORDER BY YEAR, MONTH;
