-- 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문량
SELECT
    I.INGREDIENT_TYPE,
    SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS F
LEFT JOIN ICECREAM_INFO AS I
ON F.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE
-- 총주문량이 작은 순서대로
ORDER BY TOTAL_ORDER;
