-- GRADE가 존재하는 개발자의 GRADE, ID, EMAIL을 조회
WITH GRADE_GROUPS AS (
    SELECT
        CASE
            WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') != 0
                 AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') != 0 THEN 'A'
            WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') != 0 THEN 'B'
            WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') != 0 THEN 'C'
        END AS GRADE,
        ID,
        EMAIL
    FROM DEVELOPERS
)
SELECT *
FROM GRADE_GROUPS
WHERE GRADE IS NOT NULL
-- GRADE와 ID를 기준으로 오름차순 정렬
ORDER BY GRADE, ID;
