-- 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME), 아이템의 희귀도(RARITY)
SELECT
    II.ITEM_ID,
    II.ITEM_NAME,
    II.RARITY
FROM ITEM_INFO AS II
LEFT JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
-- 더 이상 업그레이드할 수 없는 아이템
WHERE IT.PARENT_ITEM_ID IS NULL
-- 아이템 ID를 기준으로 내림차순 정렬
ORDER BY ITEM_ID DESC;
