-- 각 시간대별로 입양이 몇 건이나 발생했는지
SELECT
    HOUR(DATETIME) AS HOUR,
    COUNT(DISTINCT ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
-- 09:00부터 19:59까지
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR
-- 결과는 시간대 순으로 정렬
ORDER BY HOUR;
