-- 시간대별로 입양이 몇 건이나 발생했는지
WITH RECURSIVE HOUR_NUM AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1 AS HOUR
    FROM HOUR_NUM
    WHERE HOUR < 23
)
SELECT
    H.HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM HOUR_NUM AS H
LEFT JOIN ANIMAL_OUTS AS A
ON H.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR
-- 시간대 순으로 정렬
ORDER BY HOUR;
