WITH DURATION AS (
    SELECT
        CAR_ID, 
        HISTORY_ID,
        DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DURATION,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 60 THEN '60일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
),
DISCOUNT_INFO AS (
    SELECT
        D.HISTORY_ID,
        D.CAR_ID,
        D.RENTAL_DURATION,
        IFNULL(DC.DISCOUNT_RATE, 0) AS DISCOUNT_RATE
    FROM DURATION D
    LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON D.CAR_ID = C.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DC
    ON D.DURATION_TYPE = DC.DURATION_TYPE
        AND C.CAR_TYPE = DC.CAR_TYPE
)
-- 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력
SELECT
    DCI.HISTORY_ID,
    FLOOR(C.DAILY_FEE * (DCI.RENTAL_DURATION) * (1 - DCI.DISCOUNT_RATE / 100)) AS FEE
FROM DISCOUNT_INFO DCI
LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON DCI.CAR_ID = C.CAR_ID
-- 자동차 종류가 '트럭'인 자동차
WHERE CAR_TYPE = '트럭'
-- 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬
ORDER BY FEE DESC, HISTORY_ID DESC;
