-- 2022년 10월 16일에 대여 중인 자동차인 경우 '대여중' 이라고 표시하고, 대여 중이지 않은 자동차인 경우 '대여 가능'을 표시
WITH RENTED_AT_1016 AS (
    SELECT
        CAR_ID,
        CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN 1 ELSE 0 END AS RENTED
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
SELECT
    CAR_ID,
    CASE WHEN SUM(RENTED) >= 1 THEN '대여중' ELSE '대여 가능' END AS AVAILABILTY
FROM RENTED_AT_1016
GROUP BY CAR_ID
-- 자동차 ID를 기준으로 내림차순 정렬
ORDER BY CAR_ID DESC;
