-- 저자 별, 카테고리 별 매출액
SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS SALES
FROM BOOK_SALES AS S
JOIN BOOK AS B ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
-- 2022년 1월
WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.AUTHOR_ID, B.CATEGORY
-- 저자 ID를 오름차순으로, 저자 ID가 같다면 카테고리를 내림차순 정렬
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC;
