-- 점수, 사번, 성명, 직책, 이메일을 조회
SELECT
    SUM(G.SCORE) AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM HR_EMPLOYEES AS E
LEFT JOIN HR_DEPARTMENT AS D ON E.DEPT_ID = D.DEPT_ID
LEFT JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO
GROUP BY EMP_NO
-- 평가 점수가 가장 높은 사원 정보
ORDER BY SCORE DESC
LIMIT 1;
