-- 도서 ID(BOOK_ID), 저자명(AUTHOR_NAME), 출판일(PUBLISHED_DATE) 리스트를 출력
SELECT
    B.BOOK_ID,
    A.AUTHOR_NAME,
    DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS B
LEFT JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
-- '경제' 카테고리에 속하는 도서
WHERE B.CATEGORY = '경제'
-- 출판일을 기준으로 오름차순 정렬
ORDER BY PUBLISHED_DATE;
