-- 회원 ID, 닉네임, 총거래금액
SELECT
    U.USER_ID,
    U.NICKNAME,
    SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
-- 완료된 중고 거래
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID
-- 총금액이 70만 원 이상
HAVING SUM(B.PRICE) >= 700000
-- 총거래금액을 기준으로 오름차순 정렬
ORDER BY TOTAL_SALES;
