-- 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로 상위 3개의 맛을 조회
WITH JULY_ORDERS AS (
    SELECT
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
),
TOTAL_ORDERS AS (
    SELECT
        FH.FLAVOR, 
        FH.TOTAL_ORDER + J.TOTAL_ORDER AS SUM_ORDERS
    FROM FIRST_HALF AS FH
    LEFT JOIN JULY_ORDERS AS J ON FH.FLAVOR = J.FLAVOR

    UNION

    SELECT 
        FH.FLAVOR, 
        FH.TOTAL_ORDER + J.TOTAL_ORDER AS SUM_ORDERS
    FROM FIRST_HALF AS FH
    RIGHT JOIN JULY_ORDERS AS J ON FH.FLAVOR = J.FLAVOR
)
SELECT FLAVOR
FROM TOTAL_ORDERS
ORDER BY SUM_ORDERS DESC
LIMIT 3;
