-- 카테고리 별 도서 판매량
SELECT
    B.CATEGORY,
    SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK AS B
LEFT JOIN BOOK_SALES AS BS
ON B.BOOK_ID = BS.BOOK_ID
-- 2022년 1월
WHERE BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
-- 카테고리명을 기준으로 오름차순 정렬
ORDER BY CATEGORY;
