SELECT
    COUNT(DISTINCT ID) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    -- 평균 길이가 33cm 이상인 물고기
    -- 10cm이하의 물고기들은 10cm로 취급
    HAVING AVG(CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) >= 33
)
GROUP BY FISH_TYPE
-- 물고기 종류에 대해 오름차순으로 정렬
ORDER BY FISH_TYPE;
